RayaTask/Controllers/EmployeeController.cs
using Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RayaTask.Interface;
using RayaTask.ViewModels;

namespace RayaTask.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepo employeeRepo;

        public EmployeeController(IEmployeeRepo employeeRepo)
        {
            this.employeeRepo = employeeRepo;
        }
        public IActionResult Index()
        {

            var employees = employeeRepo.GetAll();
            ViewBag.Employees = employees;
            return View();
        }
        [HttpPost]
        //data: { Id: id, Name: name, Salary: salary, Job: job, Email: email,IsApproved:isApproved },
        [Authorize(Roles = "HRAdmin")]
        public IActionResult Edit(string Id, string Name, string Salary, string Job, string Email, string IsApproved)
        {
            if (ModelState.IsValid == false)
            {
                var errors =
                    ModelState.SelectMany(i => i.Value.Errors.Select(x => x.ErrorMessage));

                foreach (string err in errors)
                {
                    ModelState.AddModelError("", err);
                }

                return View("Index");
            }
            else
            {
                EmployeeVM employee = new EmployeeVM()
                {
                    Id = int.Parse(Id),
                    Name = Name,
                    Email = Email,
                    Job = Job,
                    Salary = double.Parse(Salary),
                    IsApproved = (int.Parse(IsApproved) == 0) ? false : true
                };
                employeeRepo.EditEmployee(employee);
                return Redirect("Index");
            }
        }

        [HttpPost]
        //        data: {  Name: nameNew, Salary: salaryNew, Job: jobNew, Email: emailNew},

        public IActionResult Add(string Name, string Salary, string Job, string Email)
        {
            if (ModelState.IsValid == false)
            {
                var errors =
                    ModelState.SelectMany(i => i.Value.Errors.Select(x => x.ErrorMessage));

                foreach (string err in errors)
                {
                    ModelState.AddModelError("", err);
                }

                return View("Index");
            }
            else
            {
                EmployeeVM employee = new EmployeeVM()
                {
                    Name = Name,
                    Email = Email,
                    Job = Job,
                    Salary = double.Parse(Salary),
                };
                employeeRepo.AddEmployee(employee);
                return Redirect("Index");
            }
        }
        [Authorize(Roles = "HRAdmin")]
        public IActionResult Delete(int Id)
        {
            employeeRepo.DeleteEmployee(Id);
            return Redirect("Index");
        }
        public IActionResult Filter(EmployeeVM emp)
        {
            var res = employeeRepo.Filter(emp);
            ViewBag.Employees = res;
            return View("Index");
        }
    }
}

RayaTask/Controllers/RolesController.cs
using Domain;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RayaTask.ViewModels;

namespace RayaTask.Controllers
{
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public UserManager<RayaUser> UserManager { get; }

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<RayaUser> userManager)
        {
            this.roleManager = roleManager;
            UserManager = userManager;
        }
        public IActionResult Index()
        {
            var data = roleManager.Roles;
            return View(data);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {

            var result = await roleManager.CreateAsync(model);

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }

            return View();
        }




        public async Task<IActionResult> Update(string id)
        {
            var data = await roleManager.FindByIdAsync(id);
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> Update(IdentityRole model)
        {

            var result = await roleManager.UpdateAsync(model);

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }
            return View(model);
        }



        public async Task<IActionResult> Delete(string id)
        {
            var data = await roleManager.FindByIdAsync(id);
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(IdentityRole model)
        {

            var data = await roleManager.FindByIdAsync(model.Id);

            if (data != null)
            {
                var result = await roleManager.DeleteAsync(data);


                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }

            return View(model);
        }
        public async Task<IActionResult> AddOrRemoveUsers(string RoleId)
        {

            ViewBag.roleId = RoleId;

            var role = await roleManager.FindByIdAsync(RoleId);

            var model = new List<UserInRoleVM>();

            foreach (var user in UserManager.Users)
            {
                var userInRole = new UserInRoleVM()
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await UserManager.IsInRoleAsync(user, role.Name))
                {
                    userInRole.IsSelected = true;
                }
                else
                {
                    userInRole.IsSelected = false;
                }

                model.Add(userInRole);
            }

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(List<UserInRoleVM> model, string RoleId)
        {

            var role = await roleManager.FindByIdAsync(RoleId);

            for (int i = 0; i < model.Count; i++)
            {

                var user = await  UserManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await UserManager.IsInRoleAsync(user, role.Name)))
                {

                    result = await UserManager.AddToRoleAsync(user, role.Name);

                }
                else if (!model[i].IsSelected && (await UserManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await UserManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

            }

            return RedirectToAction("Update", new { id = RoleId });
        }

    }
}

RayaTask/Views/Shared/_Layout.cshtml
@inject SignInManager<RayaUser> signManger

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RayaTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RayaTask.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" type="image/png" href="~/images/raya.png" />

    @RenderSection("DataTableStyles",required:false);

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RayaTask</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                       
                        <li class="nav-item float-end">
                             <a asp-action="LogOut" asp-controller="Account" class="btn btn-danger">Logout
                                        <i class="fa-solid fa-right-from-bracket"></i>
                                    </a>
                               
                           </div>
                            
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RayaTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("JqueryValidation",required:false)

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @RenderSection("DataTableScripts",required:false)
</body>
</html>